AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  DataEngineering - An Amazon S3 trigger that retrieves data from a .xlsx/.xls to a CSV file for project phoenix.
Resources:
  DataEngineeringPhoenix:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: DataEngineering-Phoenix
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: >-
        An Amazon S3 trigger that retrieves data from a .xlsx/.xls to a CSV file.
      MemorySize: 1024
      Timeout: 900
      Environment:
        Variables:
          BUCKET_NAME: domfp13-s3-bucket
      Role: arn:aws:iam::833695691939:role/DE-Lambda