AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  DataEngineering - An Amazon S3 trigger (bucket: prefix: ) that transforms data
Parameters:
  BucketNamePrefix:
    Type: String
    Default: domfp13-s3-bucket
Resources:
  DataEngineeringPhoenix:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: >-
        An Amazon S3 trigger that retrieves metadata for the object that has
        been updated.
      MemorySize: 1024
      Timeout: 450